let data = [
    [],
    [],
    [],
    [],
    [
        { day: 25, schedule: [], isMonth: false },
        { day: 26, schedule: [], isMonth: false },
        { day: 27, schedule: [], isMonth: false },
        { day: 28, schedule: [], isMonth: false },
        { day: 29, schedule: [], isMonth: false },
        { day: 30, schedule: [], isMonth: false },
        { day: 1, schedule: [], isMonth: true },
        { day: 2, schedule: [], isMonth: true },
        { day: 3, schedule: [], isMonth: true },
        { day: 4, schedule: [], isMonth: true },
        { day: 5, schedule: [], isMonth: true },
        { day: 6, schedule: [], isMonth: true },
        { day: 7, schedule: [], isMonth: true },
        { day: 8, schedule: [], isMonth: true },
        { day: 9, schedule: [], isMonth: true },
        { day: 10, schedule: [], isMonth: true },
        { day: 11, schedule: [], isMonth: true },
        { day: 12, schedule: [], isMonth: true },
        { day: 13, schedule: [], isMonth: true },
        { day: 14, schedule: [], isMonth: true },
        { day: 15, schedule: [], isMonth: true },
        { day: 16, schedule: [], isMonth: true },
        { day: 17, schedule: [], isMonth: true },
        { day: 18, schedule: [], isMonth: true },
        { day: 19, schedule: [], isMonth: true },
        { day: 20, schedule: [], isMonth: true },
        { day: 21, schedule: [], isMonth: true },
        { day: 22, schedule: [], isMonth: true },
        { day: 23, schedule: [], isMonth: true },
        { day: 24, schedule: [], isMonth: true },
        { day: 25, schedule: [], isMonth: true },
        { day: 26, schedule: [], isMonth: true },
        { day: 27, schedule: [], isMonth: true },
        { day: 28, schedule: [], isMonth: true },
        { day: 29, schedule: [], isMonth: true },
        { day: 30, schedule: [], isMonth: true },
        { day: 31, schedule: [], isMonth: true },
        { day: 1, schedule: [], isMonth: false },
        { day: 2, schedule: [], isMonth: false },
        { day: 3, schedule: [], isMonth: false },
        { day: 4, schedule: [], isMonth: false },
        { day: 5, schedule: [], isMonth: false }
    ],
    [
        { day: 30, schedule: [], isMonth: false },
        { day: 31, schedule: [], isMonth: false },
        { day: 1, schedule: [], isMonth: true },
        { day: 2, schedule: [], isMonth: true },
        { day: 3, schedule: [], isMonth: true },
        { day: 4, schedule: [], isMonth: true },
        { day: 5, schedule: [], isMonth: true },
        { day: 6, schedule: [], isMonth: true },
        { day: 7, schedule: [], isMonth: true },
        { day: 8, schedule: [], isMonth: true },
        { day: 9, schedule: [], isMonth: true },
        { day: 10, schedule: [], isMonth: true },
        { day: 11, schedule: [], isMonth: true },
        { day: 12, schedule: [], isMonth: true },
        { day: 13, schedule: [], isMonth: true },
        { day: 14, schedule: [], isMonth: true },
        { day: 15, schedule: [], isMonth: true },
        { day: 16, schedule: [], isMonth: true },
        { day: 17, schedule: [], isMonth: true },
        { day: 18, schedule: [], isMonth: true },
        { day: 19, schedule: [], isMonth: true },
        { day: 20, schedule: [], isMonth: true },
        { day: 21, schedule: [], isMonth: true },
        { day: 22, schedule: [], isMonth: true },
        { day: 23, schedule: [], isMonth: true },
        { day: 24, schedule: [], isMonth: true },
        { day: 25, schedule: [], isMonth: true },
        { day: 26, schedule: [], isMonth: true },
        { day: 27, schedule: [], isMonth: true },
        { day: 28, schedule: [], isMonth: true },
        { day: 29, schedule: [], isMonth: true },
        { day: 30, schedule: [], isMonth: true },
        { day: 1, schedule: [], isMonth: false },
        { day: 2, schedule: [], isMonth: false },
        { day: 3, schedule: [], isMonth: false },
        { day: 4, schedule: [], isMonth: false },
        { day: 5, schedule: [], isMonth: false },
        { day: 6, schedule: [], isMonth: false },
        { day: 7, schedule: [], isMonth: false },
        { day: 8, schedule: [], isMonth: false },
        { day: 9, schedule: [], isMonth: false },
        { day: 10, schedule: [], isMonth: false }
    ],
    [],
    [],
    [],
    [],
    [],
    []
]

for (let i = 0; i < 10; i++) {
    data[5][i+32] = {"day":i+1,"schedule":[],"isMonth":false}
}

console.log(data)